name: Run Asics Checker

on:
  schedule:
    - cron: "0 */2 * * *"  # Ejecutar cada 2 horas
  workflow_dispatch:  # Permite ejecución manual desde GitHub Actions

jobs:
  check-resolution:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'

      - name: Configure npm
        run: |
          npm config set registry https://registry.npmjs.org/
          npm config delete //registry.npmjs.org/:_authToken
          npm config list

      - name: Install dependencies
        run: |
          npm config set registry https://registry.npmjs.org/
          rm -rf ~/.npmrc
          npm install

      - name: Run asics-checker
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: node asics-checker.js